/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unb.cic.iris.gui.screen;

import static br.unb.cic.iris.i18n.MessageBundle.message;

import java.awt.BorderLayout;

import javax.swing.JDialog;

import br.unb.cic.iris.gui.command.GuiSendMesssageCommand;

/**
 *
 * @author pedro
 */
public class SendPanel extends javax.swing.JPanel {

    private GuiSendMesssageCommand command;
	/**
     * Creates new form SendPanel
     */
    public SendPanel() {
        initComponents();
        command = new GuiSendMesssageCommand();
    }

    public String getTo(){
    	return jTextFieldTo.getText();
    }
    
    public String getSubject(){
    	return jTextFieldSubject.getText();
    }
    
    public String getContent(){
    	return jTextAreaMessage.getText();
    }
    
    public void showInDialog(){
    	dialog = new JDialog();
    	dialog.setTitle(message("title")+" - Send Message");
    	dialog.setLayout(new BorderLayout());
    	dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    	
    	dialog.add(this);
    	
    	dialog.pack();
    	dialog.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelHeader = new javax.swing.JPanel();
        jLabelTo = new javax.swing.JLabel();
        jTextFieldTo = new javax.swing.JTextField();
        jLabelSubject = new javax.swing.JLabel();
        jTextFieldSubject = new javax.swing.JTextField();
        jPanelBody = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jPanelButton = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonSend = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelHeader.setLayout(new java.awt.GridBagLayout());

        jLabelTo.setText("To");
        jPanelHeader.add(jLabelTo, new java.awt.GridBagConstraints());

        jTextFieldTo.setColumns(30);
        jPanelHeader.add(jTextFieldTo, new java.awt.GridBagConstraints());

        jLabelSubject.setText("Subject");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanelHeader.add(jLabelSubject, gridBagConstraints);

        jTextFieldSubject.setColumns(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanelHeader.add(jTextFieldSubject, gridBagConstraints);

        add(jPanelHeader, java.awt.BorderLayout.NORTH);

        jPanelBody.setBorder(javax.swing.BorderFactory.createTitledBorder("Message"));
        jPanelBody.setLayout(new java.awt.BorderLayout());

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMessage);

        jPanelBody.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelButton.add(jButtonCancel);

        jButtonSend.setText("     Send     ");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });
        jPanelButton.add(jButtonSend);

        jPanelBody.add(jPanelButton, java.awt.BorderLayout.PAGE_END);

        add(jPanelBody, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        if(dialog != null){
        	dialog.dispose();
        }
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
       //command.execute();
    }//GEN-LAST:event_jButtonSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMessage;
    private javax.swing.JTextField jTextFieldSubject;
    private javax.swing.JTextField jTextFieldTo;
    // End of variables declaration//GEN-END:variables
	private JDialog dialog;
}
